# Remove this line once forked.
# Useful for creating extensions.
analyzer:
  exclude:
    - [build/**]
    - lib/*.g.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: ignore
    # Try to change below 'non_constant_identifier_names' to 'warning'
    # See if any warning comes up in 'Dart Analysis' for file other than '*.g.dart'
    # Solve it if possible (leave it as 'ignore' if any '*.g.dart' file is affected)
    non_constant_identifier_names: ignore
  # enable-experiment:
  # - extension-methods

# To enable rule to be checked against code for it's quality
linter:
  rules:
    #Error Rules
    - camel_case_types
    - parameter_assignments
    - avoid_empty_else
    - avoid_print
    - avoid_types_as_parameter_names
    - close_sinks
    - empty_statements
    - no_duplicate_case_values
    - valid_regexps
    #Style Rules
    # - always_put_required_named_parameters_first
    - avoid_init_to_null
    - avoid_returning_null
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - library_names
    - non_constant_identifier_names
    - prefer_conditional_assignment
    - prefer_expression_function_bodies
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - slash_for_doc_comments
    # - unnecessary_new
    - use_full_hex_values_for_flutter_colors
    - void_checks
